//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddOn
    {
        public AddOn()
        {
            this.Booking_dtc = new HashSet<Booking_dtc>();
            this.Invoice_dtc = new HashSet<Invoice_dtc>();
        }
    
        public int AId { get; set; }
        public string AName { get; set; }
        public double ARate { get; set; }
    
        public virtual ICollection<Booking_dtc> Booking_dtc { get; set; }
        public virtual ICollection<Invoice_dtc> Invoice_dtc { get; set; }
    }
}
