//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public string ApId { get; set; }
        public string ApName { get; set; }
        public int HubId { get; set; }
    
        public virtual Hub Hub { get; set; }
    }
}
