//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_hdr
    {
        public Booking_hdr()
        {
            this.Booking_dtc = new HashSet<Booking_dtc>();
            this.Invoice_dtc = new HashSet<Invoice_dtc>();
            this.Invoice_hdr = new HashSet<Invoice_hdr>();
        }
    
        public int Bid { get; set; }
        public System.DateTime Date { get; set; }
        public int CId { get; set; }
        public string BName { get; set; }
        public string BAddress { get; set; }
        public int Pin { get; set; }
        public int PhoneNo { get; set; }
        public string Email { get; set; }
        public System.DateTime Pick_Up_Date { get; set; }
        public System.DateTime Return_Date { get; set; }
        public string Pick_Up_Loc { get; set; }
        public string Return_Loc { get; set; }
        public int CarId { get; set; }
    
        public virtual ICollection<Booking_dtc> Booking_dtc { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CarClass CarClass { get; set; }
        public virtual ICollection<Invoice_dtc> Invoice_dtc { get; set; }
        public virtual ICollection<Invoice_hdr> Invoice_hdr { get; set; }
    }
}
