//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_dtc
    {
        public int Id { get; set; }
        public int Bid { get; set; }
        public int Aid { get; set; }
        public double Rate { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        public virtual Booking_hdr Booking_hdr { get; set; }
    }
}
