//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarClass
    {
        public CarClass()
        {
            this.Booking_hdr = new HashSet<Booking_hdr>();
            this.Invoice_hdr = new HashSet<Invoice_hdr>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int CarId { get; set; }
        public string CType { get; set; }
        public string CImg { get; set; }
        public double RDaily { get; set; }
        public double RWeekly { get; set; }
        public double RMonthly { get; set; }
    
        public virtual ICollection<Booking_hdr> Booking_hdr { get; set; }
        public virtual ICollection<Invoice_hdr> Invoice_hdr { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
