//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Customers = new HashSet<Customer>();
            this.Hubs = new HashSet<Hub>();
        }
    
        public int CityId { get; set; }
        public int StateId { get; set; }
        public string CityName { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Hub> Hubs { get; set; }
    }
}
