//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Booking_hdr = new HashSet<Booking_hdr>();
        }
    
        public int CId { get; set; }
        public string CName { get; set; }
        public string CAddress { get; set; }
        public int Pin { get; set; }
        public int PhoneNo { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public int CityId { get; set; }
        public int StateId { get; set; }
    
        public virtual ICollection<Booking_hdr> Booking_hdr { get; set; }
        public virtual City City { get; set; }
        public virtual State State { get; set; }
    }
}
