//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hub
    {
        public Hub()
        {
            this.Airports = new HashSet<Airport>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int HubId { get; set; }
        public string HName { get; set; }
        public string Address { get; set; }
        public int StateId { get; set; }
        public int CityId { get; set; }
    
        public virtual ICollection<Airport> Airports { get; set; }
        public virtual City City { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
