//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_hdr
    {
        public int InvId { get; set; }
        public System.DateTime IvcDate { get; set; }
        public int Bid { get; set; }
        public System.DateTime PickDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string PickLoc { get; set; }
        public string RetLoc { get; set; }
        public int CarId { get; set; }
        public int VId { get; set; }
        public double CarRentAmt { get; set; }
        public double AddOnAmt { get; set; }
        public double TotalAmt { get; set; }
    
        public virtual Booking_hdr Booking_hdr { get; set; }
        public virtual CarClass CarClass { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
