//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FleetEntitiesContext : DbContext
    {
        public FleetEntitiesContext() : base("name=FleetEntitiesContext")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AddOn> AddOns { get; set; }
        public DbSet<Airport> Airports { get; set; }
        public DbSet<Booking_dtc> Booking_dtc { get; set; }
        public DbSet<Booking_hdr> Booking_hdr { get; set; }
        public DbSet<CarClass> CarClasses { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Hub> Hubs { get; set; }
        public DbSet<Invoice_dtc> Invoice_dtc { get; set; }
        public DbSet<Invoice_hdr> Invoice_hdr { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Vehicle> Vehicles { get; set; }
    }
}
