//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Invoice_hdr = new HashSet<Invoice_hdr>();
        }
    
        public int VId { get; set; }
        public string VName { get; set; }
        public string LicNo { get; set; }
        public int HubId { get; set; }
        public int CarId { get; set; }
        public string FuelStatus { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public bool Available { get; set; }
    
        public virtual CarClass CarClass { get; set; }
        public virtual Hub Hub { get; set; }
        public virtual ICollection<Invoice_hdr> Invoice_hdr { get; set; }
    }
}
